graph LR
    Storefront <---> Middleware
    Storefront <---> Middleware
    Storefront <---> Middleware
    Storefront <---> Middleware
    Middleware <---> API
    Middleware <---> API
    Middleware <---> API
    Middleware <---> API
