flowchart LR
 subgraph s1["Storefront"]
    Browser("Browser") <-- SSR --> Server("Server")
  end
    Server <-- "server-side" --> Middleware("Middleware")
    Server <-- "fa:fa-ban" --> API("API")
    Browser <-- "client-side" --> Middleware 
    Middleware --> API
    Browser <-- "client-side" --> API

linkStyle 2 stroke:red


